language: cpp
jobs:
  include:
    - dist: trusty
      addons:
        apt:
          packages:
            - cmake
      env:
         - MATRIX_EVAL="CC=gcc && CXX=g++"

    - dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - name: "MacOS"
      os: osx
      compiler: clang

before_install:
  # install boost
    - SAVED_DIR=$(pwd)
    - cd /tmp && curl -fL https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2 -o boost_1_67_0.tar.bz2
    - tar xf ./boost_1_67_0.tar.bz2 && cd ./boost_1_67_0
    - ./bootstrap.sh --with-libraries=system
    - sudo ./b2 install
    - cd ${SAVED_DIR}

install:
    - eval "${MATRIX_EVAL}" && export CC=$CC CXX=$CXX
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j
    - cd ..

script:
    - ./build/test/unit_test

after_success:
    - bash <(curl -s https://codecov.io/bash)
