#include "common.hpp"
#include "context.hpp"

_THALLIUM_BEGIN_NAMESPACE

const char * ENVNAME_COORD_HOST = "THALLIUM_COORD_HOST";
const char * ENVNAME_COORD_PORT = "THALLIUM_COORD_PORT";
const char * ENVNAME_STARTUP_COOKIE = "THALLIUM_STARTUP_COOKIE";

_THALLIUM_END_NAMESPACE
